Сделано задание 2.1
htmlacademy-ecmascript/1806037-cinemaddict-16 pull request #4
Opened 2021-11-27 11:50 UTC by FirstBroRussia

2021-11-28 20:54 UTC, sahaviev commented on src/main.js
> +import {createLoadingFilmsListTemplate} from '/src/view/loading-films-list.js'; */
Комментарии нежелательно в PR'ах отправлять.
Лучше вообще сразу удалять код, иначе может зайти за привычку и потом всегда будет и в рабочем коде.
В нормальных команда сразу реджектят такие PR's.

2021-11-28 20:57 UTC, sahaviev commented on src/main.js
> +  }
Какая не была бы причина. Нужно придумать как написать этот код снаружи.
Я имею ввиду то что функции лучше не объявлять внутри других функций.

2021-11-28 20:58 UTC, sahaviev commented on src/main.js
> +function getCreateListFilms (data) {
Что значит название: getCreateListFilms?

2021-11-28 21:00 UTC, sahaviev commented on src/main.js
> +function getOpenFilmDetailsPopupClickHandler (evt) {
C неймингом беда конечно конкретная... Кажется тут без созвона никак =(

2021-11-28 21:05 UTC, sahaviev commented on src/view/films-list.js
> +
Это что? Что за дырки?
Лучше сразу попрошу, а то в предыдущих потоках студенты писали и ставили пустые строки просто так в шаблонах.
Пожалуйста, переставай ставить переносы строка в шаблонах. В этом нет абсолютно никакой необходимости.
Код нормально читается и без них.

2021-11-28 21:07 UTC, sahaviev commented on src/view/comments-list-popup.js
> +    </li>
А комментарии пока не должны рендериться? Это в следующих заданиях?

2021-11-28 21:09 UTC, sahaviev commented on src/utils/util.js
> +  }
Что это за магия такая? 
нужно разделить логику getRandomNumber и getRandomFractionalNumber, честно говоря, совсем не могу понять что это значит)

2021-11-28 21:10 UTC, sahaviev commented on src/mock/temporary-data.js
> +const NAME_FILMS = [
Массивы по своей сути !== константы, поэтому их лучше записать в **camelCase**.

2021-11-28 21:11 UTC, sahaviev commented on src/main.js
> +        };
Здесь тоже создается функция внутри цикла вообще. Так дело не пойдет )

2021-11-28 21:11 UTC, sahaviev commented on src/main.js
> +// mainBodyElement.insertAdjacentHTML('beforeend', createEmptyFilmsListTemplate());
Комментарии нужно поудалять.

2021-11-28 21:11 UTC, sahaviev requested changes
Оставил комментарии, завтра на консультации разберем

2021-11-30 13:06 UTC, kseniyatalstykh commented on src/main.js
> +    return renderMarkupHtmlElement(filmsListContainer, positionMarkup.BEFORE_END, createFilmCardTemplate(item));
вот тут что то странное, это не лишний код?

2021-11-30 13:36 UTC, FirstBroRussia commented on src/main.js
> +    return renderMarkupHtmlElement(filmsListContainer, positionMarkup.BEFORE_END, createFilmCardTemplate(item));
Исправлено)

2021-11-30 14:35 UTC, merged